before_install:
  - curl http://mirror.ovh.net/debian/dists/wheezy-backports/Release.gpg | sudo apt-key add -
  - echo "deb http://http.debian.net/debian wheezy-backports main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo ./tests/cfg/deploy.sh

language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies
install: 
  - pip install -e . --use-mirrors
  - pip install passlib
# command to run tests
script: "./run_test.sh"
