env:
  - TRAVIS="yes"

before_install:
  - curl https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo apt-key add -
  - echo "deb http://http.debian.net/debian wheezy-backports main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://http.debian.net/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo /sbin/ifconfig
  - sudo apt-get update -qq
  - sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
  - sudo ./tests/test_env/deploy.sh

language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies
install: 
  - pip install -e .
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
  - pip install passlib
  - pip install coveralls
# command to run tests
script: 
  - coverage run --source=ldapcherry setup.py test
  - "if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi"
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg,tests,misc . scripts/ldapcherryd; else coverage run --source=ldapcherry setup.py test; fi"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
after_success:
  - coveralls
after_failure:
  - sudo cat /var/log/syslog
