sudo: required
dist: trusty
language: python

#env:
#  - TRAVIS="yes"

before_install:
  - '[ "$TEST_PEP8" == "1" ] || sudo ./tests/test_env/deploy.sh'

python:
  - "2.7"

install: 
  - pip install -e .
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
  - pip install passlib
  - pip install coveralls

# command to run tests
#
#script: 
#  - coverage run --source=ldapcherry setup.py test
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg,tests,misc . scripts/ldapcherryd; else coverage run --source=ldapcherry setup.py test; fi"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
after_success:
  - coveralls
after_failure:
  - sudo cat /var/log/syslog
